In [1]:
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline
from schedule_ddf import sched_ddf

In [ ]:
data, schedule = sched_ddf('ELAISS1')

Academic license - for non-commercial use only - expires 2021-12-19
Using license file /Users/yoachim/Dropbox/Apps/Gurobi/gurobi.lic
> /Users/yoachim/git_repos/21_Scratch/ddf_grid/schedule_ddf.py(84)sched_ddf()
     82     import pdb ; pdb.set_trace()
     83     # Makes it go blazing fast agian, that's for sure!
---> 84     cumulative_desired = np.round(cumulative_desired)
     85 
     86     m.addConstr(cumulative_diff[0] == cumulative_sched[0] - cumulative_desired[0])

ipdb> cumulative_desired
array([  0.,   0.,   1., ..., 400., 400., 400.])
ipdb> out_season
(array([ 109,  110,  111, ..., 3539, 3540, 3541]),)
ipdb> season_mod
array([0.50317897, 0.50571719, 0.50845504, ..., 0.49613471, 0.49887256,
       0.50161041])
ipdb> sun_mask
array([ True,  True,  True, ...,  True,  True,  True])
ipdb> night_season
array([ 0.50317897,  0.50571719,  0.50845504, ..., 10.49613471,
       10.49887256, 10.50161041])
ipdb> RA
9.45


In [ ]:
schedule.max()