In [23]:
import numpy as np
from rubin_sim.scheduler.modelObservatory import Model_observatory
from rubin_sim.scheduler.utils import empty_observation
import healpy as hp
import matplotlib.pylab as plt
%matplotlib inline

In [81]:
mo = Model_observatory()

In [118]:
obs = empty_observation()

In [119]:
obs

array([(0, 0., 0., 0., 0., 0., '', 0., 0, 0., 0., 0., 0., 0., 0, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., '', 0, 0, 0, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.)],
      dtype=[('ID', '<i8'), ('RA', '<f8'), ('dec', '<f8'), ('mjd', '<f8'), ('flush_by_mjd', '<f8'), ('exptime', '<f8'), ('filter', '<U1'), ('rotSkyPos', '<f8'), ('nexp', '<i8'), ('airmass', '<f8'), ('FWHM_500', '<f8'), ('FWHMeff', '<f8'), ('FWHM_geometric', '<f8'), ('skybrightness', '<f8'), ('night', '<i8'), ('slewtime', '<f8'), ('visittime', '<f8'), ('slewdist', '<f8'), ('fivesigmadepth', '<f8'), ('alt', '<f8'), ('az', '<f8'), ('pa', '<f8'), ('clouds', '<f8'), ('moonAlt', '<f8'), ('sunAlt', '<f8'), ('note', '<U40'), ('field_id', '<i8'), ('survey_id', '<i8'), ('block_id', '<i8'), ('lmst', '<f8'), ('rotTelPos', '<f8'), ('moonAz', '<f8'), ('sunAz', '<f8'), ('sunRA', '<f8'), ('sunDec', '<f8'), ('moonRA', '<f8'), ('moonDec', '<f8'), ('moonDist', '<f8'), ('solarElong', '<f8'), ('moonPhase', '<f8'), ('cummTelAz', '<f8')])

In [120]:
obs['dec'] = np.radians(-40)
obs['RA'] = np.radians(270)
obs['rotTelPos'] = np.radians(-90)
obs['filter'] ='r'

In [121]:
ack = mo.observe(obs)

In [122]:
ack

(array([(6, 4.71238898, -0.6981317, 59853.98780671, 0., 0., 'r', 3.44163284, 0, 1.08589303, 1.06204279, 1.32776546, 1.14342321, 19.82480953, 1, 2.83756341, 0., 0., nan, 1.17038573, 4.15215008, 1.27075614, 0., 1.08880803, -0.230754, '', 0, 0, 0, 19.70309419, -1.57079633, 4.69876712, 4.50182671, 3.2772391, -0.0585506, 4.60684187, -0.46561812, 0.24850537, 1.42929517, 42.30687238, -2.14646702)],
       dtype=[('ID', '<i8'), ('RA', '<f8'), ('dec', '<f8'), ('mjd', '<f8'), ('flush_by_mjd', '<f8'), ('exptime', '<f8'), ('filter', '<U1'), ('rotSkyPos', '<f8'), ('nexp', '<i8'), ('airmass', '<f8'), ('FWHM_500', '<f8'), ('FWHMeff', '<f8'), ('FWHM_geometric', '<f8'), ('skybrightness', '<f8'), ('night', '<i8'), ('slewtime', '<f8'), ('visittime', '<f8'), ('slewdist', '<f8'), ('fivesigmadepth', '<f8'), ('alt', '<f8'), ('az', '<f8'), ('pa', '<f8'), ('clouds', '<f8'), ('moonAlt', '<f8'), ('sunAlt', '<f8'), ('note', '<U40'), ('field_id', '<i8'), ('survey_id', '<i8'), ('block_id', '<i8'), ('lmst', '<f8'), 

In [123]:
cond = mo.return_conditions()
mjd1 = cond.mjd +0

In [124]:
mjd1

array([59853.98780671])

In [125]:
obs['rotTelPos'] = np.radians(90)

ack = mo.observe(obs)

In [126]:
cond = mo.return_conditions()
mjd2 = cond.mjd +0
mjd2

array([59853.98844241])

In [127]:
(mjd2-mjd1)*24*3600

array([54.92458327])